Config = {}
Config.RealisticFlashlight = true
Config.DisableHeadshots = true
Config.DisableAimPunching = true
Config.DisplayAmmo = true
Config.DisableCrosshair = true
Config.DisableHealthRegeneration = true
Config.Weapons = {
  [GetHashKey('WEAPON_KNIFE')] = {recoil = 0.0, shake = 0.0, damage = 0.3},
  [GetHashKey('WEAPON_NIGHTSTICK')] = {recoil = 0.0, shake = 0.0, damage = 0.2},
  [GetHashKey('WEAPON_HAMMER')] = {recoil = 0.0, shake = 0.0, damage = 0.25},
  [GetHashKey('WEAPON_BAT')] = {recoil = 0.0, shake = 0.0, damage = 0.3},
  [GetHashKey('WEAPON_GOLFCLUB')] = {recoil = 0.0, shake = 0.0, damage = 0.3},
  [GetHashKey('WEAPON_CROWBAR')] = {recoil = 0.0, shake = 0.0, damage = 0.25},
  [GetHashKey('WEAPON_PISTOL')] = {recoil = 0.6, shake = 0.1, damage = 0.18},
  [GetHashKey('WEAPON_COMBATPISTOL')] = {recoil = 0.7, shake = 0.15, damage = 0.19},
  [GetHashKey('WEAPON_APPISTOL')] = {recoil = 2.75, shake = 2.15, damage = 0.2},
  [GetHashKey('WEAPON_SMG')] = {recoil = 0.65, shake = 0.1, damage = 0.22},
  [GetHashKey('WEAPON_MICROSMG')] = {recoil = 0.7, shake = 0.15, damage = 0.18},
  [GetHashKey('WEAPON_ASSAULTRIFLE')] = {recoil = 0.85, shake = 0.2, damage = 0.3},
  [GetHashKey('WEAPON_CARBINERIFLE')] = {recoil = 0.8, shake = 0.15, damage = 0.28},
  [GetHashKey('WEAPON_ADVANCEDRIFLE')] = {recoil = 0.75, shake = 0.15, damage = 0.26},
  [GetHashKey('WEAPON_MG')] = {recoil = 1.0, shake = 0.25, damage = 0.33},
  [GetHashKey('WEAPON_COMBATMG')] = {recoil = 0.9, shake = 0.2, damage = 0.35},
  [GetHashKey('WEAPON_PUMPSHOTGUN')] = {recoil = 1.2, shake = 0.3, damage = 0.45},
  [GetHashKey('WEAPON_SAWNOFFSHOTGUN')] = {recoil = 1.3, shake = 0.35, damage = 0.5},
  [GetHashKey('WEAPON_ASSAULTSHOTGUN')] = {recoil = 1.1, shake = 0.3, damage = 0.4},
  [GetHashKey('WEAPON_BULLPUPSHOTGUN')] = {recoil = 1.0, shake = 0.25, damage = 0.38},
  [GetHashKey('WEAPON_STUNGUN')] = {recoil = 0.0, shake = 0.0, damage = 0.0},
  [GetHashKey('WEAPON_SNIPERRIFLE')] = {recoil = 1.6, shake = 0.4, damage = 0.6},
  [GetHashKey('WEAPON_HEAVYSNIPER')] = {recoil = 1.8, shake = 0.45, damage = 0.7},
  [GetHashKey('WEAPON_REMOTESNIPER')] = {recoil = 0.0, shake = 0.0, damage = 0.0},
  [GetHashKey('WEAPON_GRENADELAUNCHER')] = {recoil = 1.0, shake = 0.35, damage = 0.5},
  [GetHashKey('WEAPON_RPG')] = {recoil = 1.5, shake = 0.5, damage = 0.65},
  [GetHashKey('WEAPON_MINIGUN')] = {recoil = 1.0, shake = 0.3, damage = 0.25},
  [GetHashKey('WEAPON_GRENADE')] = {recoil = 0.0, shake = 0.0, damage = 0.45},
  [GetHashKey('WEAPON_STICKYBOMB')] = {recoil = 0.0, shake = 0.0, damage = 0.55},
  [GetHashKey('WEAPON_SMOKEGRENADE')] = {recoil = 0.0, shake = 0.0, damage = 0.0},
  [GetHashKey('WEAPON_BZGAS')] = {recoil = 0.0, shake = 0.0, damage = 0.0},
  [GetHashKey('WEAPON_MOLOTOV')] = {recoil = 0.0, shake = 0.0, damage = 0.3},
  [GetHashKey('WEAPON_FIREEXTINGUISHER')] = {recoil = 0.0, shake = 0.0, damage = 0.0},
  [GetHashKey('WEAPON_PETROLCAN')] = {recoil = 0.0, shake = 0.0, damage = 0.0},
  [GetHashKey('WEAPON_BALL')] = {recoil = 0.0, shake = 0.0, damage = 0.0},
  [GetHashKey('WEAPON_FLARE')] = {recoil = 0.0, shake = 0.0, damage = 0.0},
  [GetHashKey('WEAPON_BOTTLE')] = {recoil = 0.0, shake = 0.0, damage = 0.25},
  [GetHashKey('WEAPON_GUSENBERG')] = {recoil = 0.8, shake = 0.2, damage = 0.28},
  [GetHashKey('WEAPON_SPECIALCARBINE')] = {recoil = 0.8, shake = 0.2, damage = 0.27},
  [GetHashKey('WEAPON_HEAVYPISTOL')] = {recoil = 0.7, shake = 0.1, damage = 0.22},
  [GetHashKey('WEAPON_DOUBLEACTION')] = {recoil = 0.75, shake = 0.15, damage = 0.25},
  [GetHashKey('WEAPON_MARKSMANRIFLE')] = {recoil = 1.0, shake = 0.25, damage = 0.35},
  [GetHashKey('WEAPON_MUSKET')] = {recoil = 1.2, shake = 0.3, damage = 0.45},
  [GetHashKey('WEAPON_RAYPISTOL')] = {recoil = 0.5, shake = 0.05, damage = 0.25},
  [GetHashKey('WEAPON_RAYCARBINE')] = {recoil = 0.7, shake = 0.1, damage = 0.3},
  [GetHashKey('WEAPON_RAYMINIGUN')] = {recoil = 1.2, shake = 0.3, damage = 0.4},
  [GetHashKey('WEAPON_NAVYREVOLVER')] = {recoil = 0.8, shake = 0.15, damage = 0.35},
  [GetHashKey('WEAPON_WRENCH')] = {recoil = 0.0, shake = 0.0, damage = 0.3},
  [GetHashKey('WEAPON_FLASHLIGHT')] = {recoil = 0.0, shake = 0.0, damage = 0.0},
  [GetHashKey('WEAPON_GROZA')] = {recoil = 0.85, shake = 0.2, damage = 0.33},
  [GetHashKey('WEAPON_DRACO')] = {recoil = 0.8, shake = 0.2, damage = 0.35},
  [GetHashKey('WEAPON_GEPARD')] = {recoil = 1.0, shake = 0.3, damage = 0.4},
  [GetHashKey('WEAPON_M4A1')] = {recoil = 0.85, shake = 0.2, damage = 0.32},
  [GetHashKey('WEAPON_870')] = {recoil = 0.7, shake = 0.15, damage = 0.25},
  [GetHashKey('WEAPON_M4')] = {recoil = 0.7, shake = 0.15, damage = 0.25},
  [GetHashKey('WEAPON_X23')] = {recoil = 0.7, shake = 0.15, damage = 0.25},
  [GetHashKey('WEAPON_x26')] = {recoil = 0.7, shake = 0.15, damage = 0.25},
  [GetHashKey('WEAPON_GLOCK22')] = {recoil = 0.7, shake = 0.15, damage = 0.25},
  [GetHashKey('WEAPON_BANNER')] = {recoil = 0.0, shake = 0.0, damage = 0.0}
}
